name: Scheduled Node.js Job

on:
  schedule:
    - cron: '0 21 * * *'  # 2:00 PM Los Angeles Time (PDT)
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run index1.js
        run: node index1.js
        env:
          NODE_ENV: production
          config: ${{ secrets.env_config }}

      - name: Run index2.js
        run: node index2.js
        env:
          NODE_ENV: production
          config: ${{ secrets.env_config }}
